/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    McpAuthToken: {
      type: "sst.sst.Secret"
      value: string
    }
    OriginAccessClientId: {
      type: "sst.sst.Secret"
      value: string
    }
    OriginAccessClientSecret: {
      type: "sst.sst.Secret"
      value: string
    }
    PublicUrl: {
      type: "sst.sst.Linkable"
      value: string
    }
    VaultCortexApi: {
      type: "sst.aws.ApiGatewayV2"
      url: string
    }
  }
}

import "sst"
export {}
