export type LocalEnvAnswers = {
  mcpAuthToken: string
  vaultPath: string
}

export type RemoteEnvAnswers = {
  mcpAuthToken: string
  publicUrl: string
  /** Empty string when the user chose to fill it in later. */
  obsidianAuthToken: string
  vaultName: string
  /** Only set when the vault uses end-to-end encryption. */
  vaultPassword?: string
}

// The optional blocks mirror the canonical deploy/<mode>/.env.example files.
// cli/src/templates.test.ts asserts every required `${VAR:?}` in the compose
// templates has a matching line here, so a new required var breaks CI until
// these builders learn it.

const LOCAL_OPTIONAL_BLOCK = `# Optional ──────────────────────────────────────────────────
# To override a setting: uncomment it, set a value, then apply with
# "docker compose up -d" (restart alone does not re-read this file).

# Your IANA timezone — affects daily note resolution and memory timestamps.
# TZ=America/New_York

# Enable or disable the embedding pipeline (default: true).
# When true, notes are chunked and embedded via a local ONNX model
# (bge-small-en-v1.5) for hybrid search — FTS5 keyword + vector semantic
# similarity fused via RRF. First startup is slow (~5min for 700 notes);
# subsequent starts are fast via content-hash caching.
# Set to false to disable model download and use FTS5 search only.
# EMBEDDING_ENABLED=true

# Reranking mode for hybrid search results (default: blended).
# "blended" uses a cross-encoder to refine result ordering with
# position-aware score blending (~200ms added latency).
# "none" skips reranking for lower latency.
# Only takes effect when EMBEDDING_ENABLED=true.
# RERANK_MODE=blended

# Enable or disable the memory layer (default: true).
# Set to false to hide memory tools and skip About Me/ creation.
# MEMORY_ENABLED=true
# Memory folder name in your vault (default: About Me).
# MEMORY_DIR=About Me

# Host port to expose (default: 8000).
# PORT=8000

# Log verbosity: debug | info | warn | error (default: info).
# LOG_LEVEL=info

# Directory for persistent log files inside the container.
# Unset by default — logs go to stdout only. Set a path to also write
# date-stamped log files there (the /data volume persists them).
# LOG_DIR=/data/logs

# Days to retain persistent log files before cleanup (default: 30).
# LOG_RETENTION_DAYS=30

# Windows users: set this to true. Makes a vault stored on a C: drive work
# through Docker Desktop (switches the file watcher to polling and note moves
# to rename-based writes). Only strictly needed when your vault is on a C:
# drive rather than inside WSL2, but harmless to enable for any Windows setup.
# WINDOWS_MODE=true
`

const REMOTE_OPTIONAL_BLOCK = `# Optional ──────────────────────────────────────────────────
# To override a setting: uncomment it, set a value, then apply with
# "docker compose up -d" (restart alone does not re-read this file).

# Your IANA timezone — affects daily note resolution and memory timestamps.
# TZ=America/New_York

# Enable or disable the embedding pipeline (default: true).
# When true, notes are chunked and embedded via a local ONNX model
# (bge-small-en-v1.5) for hybrid search — FTS5 keyword + vector semantic
# similarity fused via RRF. First startup is slow (~5min for 700 notes);
# subsequent starts are fast via content-hash caching.
# Set to false to disable model download and use FTS5 search only.
# EMBEDDING_ENABLED=true

# Reranking mode for hybrid search results (default: blended).
# "blended" uses a cross-encoder to refine result ordering with
# position-aware score blending (~200ms added latency).
# "none" skips reranking for lower latency.
# Only takes effect when EMBEDDING_ENABLED=true.
# RERANK_MODE=blended

# Enable or disable the memory layer (default: true).
# Set to false to hide memory tools and skip About Me/ creation.
# MEMORY_ENABLED=true
# Memory folder name in your vault (default: About Me).
# MEMORY_DIR=About Me

# Host port to expose (default: 8000).
# PORT=8000

# Log verbosity: debug | info | warn | error (default: info).
# LOG_LEVEL=info

# Directory for persistent log files inside the container (default: /data/logs).
# Set to empty to disable file logging (logs still go to stdout either way).
# LOG_DIR=/data/logs

# Days to retain persistent log files before cleanup (default: 30).
# LOG_RETENTION_DAYS=30

# User/group IDs for obsidian-sync (default: 1000).
# PUID=1000
# PGID=1000

# Device name shown in Obsidian Sync settings.
# DEVICE_NAME=vault-cortex

# Obsidian Sync conflict resolution: merge | conflict (default: merge).
# CONFLICT_STRATEGY=merge

# Sync direction: bidirectional | pull-only | push-only (default: bidirectional).
# SYNC_MODE=bidirectional
`

export const buildLocalEnv = (
  answers: LocalEnvAnswers,
): string => `# vault-cortex — local quickstart
# Generated by \`npx vault-cortex init\`. Full option reference:
# https://github.com/aliasunder/vault-cortex/blob/main/deploy/local/.env.example

# Required ──────────────────────────────────────────────────

# Bearer token for MCP authentication (auto-generated).
MCP_AUTH_TOKEN=${answers.mcpAuthToken}

# Absolute path to your Obsidian vault on this machine.
VAULT_PATH=${answers.vaultPath}

${LOCAL_OPTIONAL_BLOCK}`

export const buildRemoteEnv = (answers: RemoteEnvAnswers): string => {
  const vaultPasswordLines =
    answers.vaultPassword === undefined
      ? `# Only if your vault has end-to-end encryption enabled.
# VAULT_PASSWORD=`
      : `# Vault end-to-end encryption password.
VAULT_PASSWORD=${answers.vaultPassword}`

  const obsidianTokenComment =
    answers.obsidianAuthToken === ""
      ? `# Obsidian Sync auth token — FILL THIS IN before docker compose up.
# Generate once with:
#   docker run --rm -it --entrypoint get-token \\
#     ghcr.io/belphemur/obsidian-headless-sync-docker:latest`
      : `# Obsidian Sync auth token.`

  return `# vault-cortex — remote quickstart (Obsidian Sync)
# Generated by \`npx vault-cortex init\`. Full option reference:
# https://github.com/aliasunder/vault-cortex/blob/main/deploy/remote/.env.example

# Required ──────────────────────────────────────────────────

# Bearer token for MCP authentication (auto-generated).
MCP_AUTH_TOKEN=${answers.mcpAuthToken}

# Public URL that MCP clients use to reach this server.
# Used as the OAuth issuer URL in discovery metadata.
PUBLIC_URL=${answers.publicUrl}

${obsidianTokenComment}
OBSIDIAN_AUTH_TOKEN=${answers.obsidianAuthToken}

# Exact name of your Obsidian vault (case-sensitive).
VAULT_NAME=${answers.vaultName}

${vaultPasswordLines}

${REMOTE_OPTIONAL_BLOCK}`
}
